version: '3.8'

services:
  # Serviço do Site (Django)
  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=sistema_despachante_db
      - DB_USER=postgres
      - DB_PASS=121166  # <--- Coloque a mesma senha do db abaixo

  # Serviço do Banco (PostgreSQL)
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sistema_despachante_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=121166 # <--- Senha do banco

volumes:
  postgres_data: